### ISSUE TITLE
Ordering of compatibility matrix columns

### ISSUE THREAD

**Issue by minhqdao** [fortran-lang/setup-fortran#102]
The compatibility matrix is currently ordered the following way:

intel-classic 2021.1.2 -> intel-classic 2021.10 -> ... -> intel-classic 2021.2

It would be great to have it ordered according to their numeric values:

intel-classic 2021.1.2 -> intel-classic 2021.2 -> ... -> intel-classic 2021.10

It would make it easier to find the latest release of a compiler.

Screenshot:

<img width="591" alt="Screenshot 2024-07-28 at 15 16 41" src="https://github.com/user-attachments/assets/a07e9863-a49a-4939-9323-05d18a931983">

**Comment by wpbonelli** [comment]
closed by #103
