### ISSUE TITLE
Switch to javascript action

### ISSUE THREAD

**Issue by awvwgk** [fortran-lang/setup-fortran#2]
Required for using caching and setting of environment variables (updating `PATH`, `CPATH`, `LIBRARY_PATH`, ...).

**Comment by tueda** [comment]
For reference: It is easy to update environment variables in shell scripts:

- [Workflow commands for GitHub Actions - Setting an environment variable](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-environment-variable)

Example:
https://github.com/tueda/setup-fortran/blob/081aca7c925c021124f9de8232532738b7d7414b/scripts/_setup-fin.sh#L50

Caching files also does not absolutely require JavaScript and can be done in a composite action with https://github.com/actions/cache, though it may be a bit complicated.

Example:
https://github.com/awalsh128/cache-apt-pkgs-action

**Comment by wpbonelli** [comment]
Maybe worth it if a need arises but at the moment I don't see a downside to keeping this a composite action, and saves us the effort of rewriting in JS. But please reopen @awvwgk if you disagree
