### ISSUE TITLE
Sometimes failed CI workflows

### ISSUE THREAD

**Issue by kohei-noda-qcrg** [fortran-lang/setup-fortran#22]
A scheduled CI workflow has been set up for this repository. However, the CI workflow sometimes fails. This is because the Report compatibility job automatically returns an error because the test job continues to run for more than a day without the Report compatibility job running.

According to the test of my forked repository, the total duration of this repository's CI is about 13 minutes.
https://github.com/kohei-noda-qcrg/setup-fortran/actions/runs/5577205876
(This CI is just trying to automatically create a pull request to awvwgk/setup-fortran and failing, so don't worry about Report Compatibility failing!)

However, the total duration time of CI in this repository is significantly longer after [this scheduled CI](https://github.com/awvwgk/setup-fortran/actions/runs/5097338228), and the probability of test failure has also increased!

The problem reported by @w-bonelli  in the following comment seems to be related to this issue.
https://github.com/awvwgk/setup-fortran/pull/16#issuecomment-1637165718

But I am not sure how to resolve this problem.
@awvwgk
Do you have any opinions or solutions?

**Comment by w-bonelli** [comment]
I suspect @awvwgk has this repo configured for self-hosted runners.

**Comment by wpbonelli** [comment]
CI seems fine now after the move to fortran-lang org
