### ISSUE TITLE
Shipping cross-compiler compatible FC compiler -- Mac

### ISSUE THREAD

**Issue by zerothi** [fortran-lang/setup-fortran#35]
The current homebrew FC compiler does not support cross compilation.

This can make it difficult to create binaries for arm processor (M1, M2) on Mac's using default github actions since we don't have access to the M1 processors.

I don't have a big experience with where these compilers exists in the homebrew ecosystem, but https://docs.brew.sh/Custom-GCC-and-cross-compilers seems to suggest we can access them pretty easily.

**Comment by wpbonelli** [comment]
[This](https://github.com/actions/runner-images/issues/8439#issuecomment-1755601587) suggests Apple silicon runners will be free for public projects eventually so I doubt this is worth the effort, if possible at all. But if you have a solution please feel free to open a PR.

**Comment by kgantchev** [comment]
> [This](https://github.com/actions/runner-images/issues/8439#issuecomment-1755601587) suggests Apple silicon runners will be free for public projects eventually so I doubt this is worth the effort, if possible at all. But if you have a solution please feel free to open a PR.

@wpbonelli 
You can use the [FlyCI](https://www.flyci.net/)'s M1 and M2 runners. Our runners are on average 2x faster and 2x cheaper than GitHub's **AND** we have a free tier for OSS projects (see below).

## Install Instructrions 

Easily replace your M1 runners: 
```diff
jobs:
 ci:
-    runs-on: macos-latest
+    runs-on: flyci-macos-large-latest-m1
   steps:
   - name: 👀 Checkout repo
     uses: actions/checkout@v4
```

Or try the M2 runners: 
```diff
jobs:
  ci:
-    runs-on: macos-latest
+    runs-on: flyci-macos-large-latest-m2
    steps:
      - name: 👀 Checkout repo
        uses: actions/checkout@v4
 ```

## Pricing  

| Processor | vCPU | RAM (GB) | Storage | Label | Price on FlyCI | Price on GitHub |
|-----------|-------|-----------|----------|-------------------------------|----------------|-----------------|
| M1        | 4    | 7        | 28 GB | flyci-macos-large-latest-m1   | $0.06          | -             |
| M1        | 8    | 14       | 28 GB | flyci-macos-xlarge-latest-m1  | $0.12          | $0.16           |
| M2        | 4    | 7        | 28 GB | flyci-macos-large-latest-m2   | $0.08          | -             |
| M2        | 8    | 14       | 28 GB | flyci-macos-xlarge-latest-m2  | $0.16          | -             |

## 500 mins/month Free for Public Repos

If your repo is public, then FlyCI offers 500 mins/month of free M1 runner usage with the `flyci-macos-large-latest-m1` runner.  

Best Regards,
Kiril Gantchev
CEO and co-founder of [FlyCI](https://flyci.net)
