### ISSUE TITLE
Project maintenance

### ISSUE THREAD

**Issue by awvwgk** [fortran-lang/setup-fortran#38]
@wpbonelli offered to co-maintain this action, I am happy to make this a shared effort under an existing or new organization in GitHub.

@certik, @milancurcic, @gnikit, @lkedward, this action could be maintained under the @fortran-lang organization. Any objections against this transfer?

**Comment by gnikit** [comment]
+1 to come under fortran-lang!

**Comment by milancurcic** [comment]
Sounds good to me, thanks @awvwgk and @wpbonelli!

**Comment by certik** [comment]
Go for it under fortran-lang.

**Comment by awvwgk** [comment]
Transferred to @fortran-lang. I also invited @wpbonelli to @fortran-lang to provide access to this repo.

**Comment by wpbonelli** [comment]
Thanks all, accepted invitation. Happy to help out.

**Comment by awvwgk** [comment]
@wpbonelli, can you check whether the @fortran-lang/actions team gives you access to this repo?

For all changes to the repo, I still recommend to stay with the fork and PR workflow rather than creating branches in the production repo here.

**Comment by wpbonelli** [comment]
looks like I have write access and can run/cancel actions. thanks!
