### ISSUE TITLE
Set up `ifort` *without* C/C++ compiler?

### ISSUE THREAD

**Issue by alexdewar** [fortran-lang/setup-fortran#47]
I currently have a project which uses Fortran and C++. The problem is that I want to compile the C++ code with MSVC and this action makes the Intel compiler the default for C++ and I can't find a way to unset it.

Any ideas?

**Comment by wpbonelli** [comment]
Is invoking `cl` directly not an option? Does setting `CC/CXX=cl` not work for your build system?

**Comment by alexdewar** [comment]
I'd set `CXX=cl` but I'd forgotten about `CC`. My bad. Thanks for your response!

**Comment by wpbonelli** [comment]
Np! Glad it's working for you
