### ISSUE TITLE
Node.js 16 deprecation warning message

### ISSUE THREAD

**Issue by jalvesz** [fortran-lang/setup-fortran#75]
Hi,

I ran an action using setup-fpm@v5 and got the following warning:
> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: fortran-lang/setup-fpm@v5. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

Have you seen this before? should I use a different version of the setup-fpm?

**Comment by jalvesz** [comment]
Ups, sorry, problem with setup-fpm and not setup-fortran, I'll close the issue here and transfer to the appropriate repo.

Cheers,

**Comment by gnikit** [comment]
I need to setup dependabot updates for it, but I'm slightly short on time these days.
