### ISSUE TITLE
Intel 2023.1.0 option: typo in URL address

### ISSUE THREAD

**Issue by perazz** [fortran-lang/setup-fortran#77]
It works anyways in the CI, but I believe this is a typo in the following URL: 

https://github.com/fortran-lang/setup-fortran/blob/2a11c57ecf26d40ea43d66a33f9f6fc4d593d6f8/setup-fortran.sh#L401-L402

My proposed fix is at PR #76. 

Thank you @fortran-lang/admins @wpbonelli

**Comment by wpbonelli** [comment]
Thanks @perazz. Looks like it worked before because [curl is forgiving](https://curl.se/docs/url-syntax.html) about slash counts

![Screenshot 2024-03-26 at 10 54 55 AM](https://github.com/fortran-lang/setup-fortran/assets/10502868/d0740d11-23fd-40bc-968d-f05ccabdf1af)
